name: Publish SDK to Maven Central

on:
  push:
    branches: [ main ]

jobs:
  publish:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: 'maven'
        
    - name: Import GPG key
      uses: crazy-max/ghaction-import-gpg@v6
      with:
        gpg_private_key: ${{ secrets.GPG_PRIVATE_KEY }}
        passphrase: ${{ secrets.GPG_PASSPHRASE }}
        
    - name: Setup Maven settings.xml
      run: |
        mkdir -p ~/.m2
        cp .github/workflows/settings.xml ~/.m2/
        
    - name: Build and publish to Maven Central
      working-directory: ./apps
      env:
        MAVEN_USERNAME: ${{ secrets.SONATYPE_USERNAME }}
        MAVEN_PASSWORD: ${{ secrets.SONATYPE_PASSWORD }}
        GPG_PASSPHRASE: ${{ secrets.GPG_PASSPHRASE }}
      run: |
        mvn clean deploy -B -Dgpg.passphrase=${{ secrets.GPG_PASSPHRASE }} -P release
        
    - name: Complete Publishing to Maven Central
      uses: actions/github-script@v6
      with:
        script: |
          const url = "https://central.sonatype.com/publishing/deployments";
          console.log(`Publishing completed. Visit ${url} to finalize the deployment if required.`);
          core.notice(`Publishing completed. Visit ${url} to finalize the deployment if required.`);
