name: Publish SDK to Maven Central
env:
  SONATYPE_PASSWORD: ${{ secrets.SONATYPE_PASSWORD }}
  SONATYPE_USERNAME: ${{ secrets.SONATYPE_USERNAME }}

on:
  push:
    branches: 
      - main
  pull_request:
    branches: 
      - main

jobs:
  publish:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./apps

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up JDK 21
      uses: actions/setup-java@v4
      with:
        java-version: '21'
        distribution: 'temurin'
        cache: maven

    - name: Configure GPG Key
      run: |
        mkdir -p ~/.gnupg
        echo "${{ secrets.GPG_PRIVATE_KEY }}" | gpg --batch --import
        gpg --list-secret-keys --keyid-format LONG
        echo "use-agent" >> ~/.gnupg/gpg.conf
        echo "pinentry-mode loopback" >> ~/.gnupg/gpg.conf
        echo "allow-loopback-pinentry" >> ~/.gnupg/gpg-agent.conf
        chmod 700 ~/.gnupg

    - name: Maven Build with GPG Sign
      run: |
          export GPG_TTY=$(tty)
          mvn clean install -Dgpg.executable=gpg -Dgpg.keyname=BCFBE978045CC9F0 -Dgpg.passphrase="${{ secrets.GPG_PASSPHRASE }}" -DskipTests




    - name: Create settings.xml for Maven Central
      run: |
        mkdir -p $HOME/.m2
        cat > $HOME/.m2/settings.xml << EOF
        <settings xmlns="http://maven.apache.org/SETTINGS/1.0.0"
                  xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
                  xsi:schemaLocation="http://maven.apache.org/SETTINGS/1.0.0 http://maven.apache.org/xsd/settings-1.0.0.xsd">
          <servers>
            <server>
              <id>central</id>
              <username>${{ secrets.SONATYPE_USERNAME }}</username>
              <password>${{ secrets.SONATYPE_PASSWORD }}</password>
            </server>
          </servers>
          <profiles>
            <profile>
              <id>gpg</id>
              <properties>
                <gpg.executable>gpg</gpg.executable>
                <gpg.passphrase>${{ secrets.GPG_PASSPHRASE }}</gpg.passphrase>
              </properties>
            </profile>
          </profiles>
          <activeProfiles>
            <activeProfile>gpg</activeProfile>
          </activeProfiles>
        </settings>
        EOF

    - name: Build with Maven
      run: mvn -B clean compile

    - name: Run tests
      run: mvn -B test

    - name: Package, Sign, and Publish to Maven Central
      run: |
        export GPG_TTY=$(tty)
        mvn -B deploy -DskipTests \
          -Dgpg.passphrase="${{ secrets.GPG_PASSPHRASE }}" \
          -Dgpg.keyname="${{ secrets.GPG_KEY_ID }}" \
          -Dgpg.homedir=~/.gnupg \
          -X
          
    - name: Auto-publish to Maven Central
      run: |
        sudo apt-get install -y jq
        DEPLOYMENT_ID=$(curl -s -X GET -u ${{ secrets.SONATYPE_USERNAME }}:${{ secrets.SONATYPE_PASSWORD }} \
          "https://central.sonatype.com/api/v1/publisher/deployment?filter=status:VALIDATION_PASSED" | \
          jq -r '.items[0].id')

        if [ -n "$DEPLOYMENT_ID" ] && [ "$DEPLOYMENT_ID" != "null" ]; then
          curl -X POST -u ${{ secrets.SONATYPE_USERNAME }}:${{ secrets.SONATYPE_PASSWORD }} \
            "https://central.sonatype.com/api/v1/publisher/deployment/$DEPLOYMENT_ID/publish"
          echo "Published deployment ID: $DEPLOYMENT_ID"
        else
          echo "No valid deployment found to publish"
          exit 1
        fi
