name: Publish to Maven Central

on:
  push:
    branches: [ main ]

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven

      - name: Import GPG key
        uses: crazy-max/ghaction-import-gpg@v5
        with:
          gpg_private_key: ${{ secrets.GPG_PRIVATE_KEY }}
          passphrase: ${{ secrets.GPG_PASSPHRASE }}

      - name: Setup Maven settings.xml
        uses: s4u/maven-settings-action@v2.8.0
        with:
          servers: |
            [{
              "id": "central",
              "username": "${{ secrets.SONATYPE_USERNAME }}",
              "password": "${{ secrets.SONATYPE_PASSWORD }}"
            }]

      - name: Build and publish to Maven Central
        run: |
          mvn clean deploy -B -Dgpg.passphrase=${{ secrets.GPG_PASSPHRASE }}

      - name: Publish deployment to Maven Central
        run: |
          # Extract deployment ID from the logs
          DEPLOYMENT_ID=$(grep -o 'deploymentId: [0-9a-f-]*' target/maven-central.log | tail -1 | awk '{print $2}')
          
          if [ -n "$DEPLOYMENT_ID" ]; then
            echo "Publishing deployment with ID: $DEPLOYMENT_ID"
            
            # Create JSON payload for the publish API
            cat > publish_payload.json << EOF
            {
              "deploymentId": "$DEPLOYMENT_ID",
              "autoPublish": true
            }
            EOF
            
            # Call the Sonatype Central API to publish
            curl -X POST \
              -H "Content-Type: application/json" \
              -H "Authorization: Bearer ${{ secrets.SONATYPE_PASSWORD }}" \
              -d @publish_payload.json \
              https://central.sonatype.com/api/v1/publisher/publish
          else
            echo "Failed to find deployment ID in logs"
            exit 1
          fi
