name: Build and Release

on:
  push:
    branches:
      - main
    tags:
      - 'v*.*.*'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Setup Java
        uses: actions/setup-java@v3
        with:
          java-version: '21'
          distribution: 'adopt'

      - name: Setup GPG Key
        run: |
          # Ensure the .gnupg directory exists with correct permissions
          mkdir -p ~/.gnupg
          chmod 700 ~/.gnupg

          # Import the GPG key from GitHub Secrets
          echo "${{ secrets.GPG_PRIVATE_KEY }}" | gpg --batch --import

          # Configure GPG for non-interactive usage
          echo "use-agent" >> ~/.gnupg/gpg.conf
          echo "pinentry-mode loopback" >> ~/.gnupg/gpg.conf
          echo "allow-loopback-pinentry" >> ~/.gnupg/gpg-agent.conf

          # Set environment variables
          export GNUPGHOME=~/.gnupg
          export GPG_TTY=$(tty)

          # Verify the GPG key import
          gpg --list-secret-keys --keyid-format LONG
          
      - name: Build and Sign with Maven
        env:
          GPG_PASSPHRASE: ${{ secrets.GPG_PASSPHRASE }}
        run: |
          # Build and sign the project
          mvn clean install \
            -Dgpg.executable=gpg \
            -Dgpg.keyname=BCFBE978045CC9F0 \
            -Dgpg.passphrase="${{ secrets.GPG_PASSPHRASE }}" \
            -Dgpg.hom=~/.gnupg \
            -DskipTests

      - name: Publish to Maven Central
        run: |
          mvn deploy -Dgpg.passphrase="${{ secrets.GPG_PASSPHRASE }}" -DskipTests
